# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3223b460c9d6a6c56021232dc6efd734568668aaa85befa5fb6687c9bcb5eaff767ce5842157f14c1f28b57c8641cc0b95c2fae9ed03fb43c6f644bde3543ef6

test:
  secret_key_base: f45e7e2712304b35a6c3b2c929f1bcf629ffc0326628f8cb1de9abc9d0a176aa964359a506168e8d9bf826316e168ab0544a7908489b836422d8499d847450a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
